from __future__ import annotations

from typing import Any


def build_relation_turn_frame(
    *,
    run_id: str,
    generated_at: str,
    status: str,
    relation_subject_ref: str | None,
    relation_stage: str | None,
    shared_language_refs: list[str],
    commitment_truth_refs: list[str],
    last_contact_refs: list[str],
    boundary_state: str,
    source_doc_refs: list[str],
    readme_block_refs: list[str],
    runtime_carrier_refs: list[str],
) -> dict[str, Any]:
    return {
        "schema_version": "relation_turn_frame_v0",
        "run_id": run_id,
        "generated_at": generated_at,
        "status": status,
        "relation_turn_id": f"relation-turn-{run_id}",
        "relation_subject_ref": relation_subject_ref,
        "relation_stage": relation_stage,
        "shared_language_refs": shared_language_refs,
        "commitment_truth_refs": commitment_truth_refs,
        "last_contact_refs": last_contact_refs,
        "boundary_state": boundary_state,
        "source_doc_refs": source_doc_refs,
        "readme_block_refs": readme_block_refs,
        "runtime_carrier_refs": runtime_carrier_refs,
    }


def build_turn_transition_trace(
    *,
    run_id: str,
    generated_at: str,
    status: str,
    turn_stage: str,
    life_context_ref: str,
    relation_turn_ref: str,
    relation_scope_ref: str | None,
    expression_monitor_restore_refs: list[str],
    unresolved_commitment_refs: list[str],
    context_accumulation_restore_refs: list[str],
    language_percept_restore_refs: list[str],
    semantic_map_restore_refs: list[str],
    waiting_heartbeat_ref: str,
    next_required_action: str,
    source_doc_refs: list[str],
    readme_block_refs: list[str],
    runtime_carrier_refs: list[str],
) -> dict[str, Any]:
    return {
        "schema_version": "turn_transition_trace_v0",
        "run_id": run_id,
        "generated_at": generated_at,
        "status": status,
        "transition_kind": "birth_restore_to_first_terminal_turn",
        "from_stage": "ready_for_first_terminal_turn",
        "to_stage": turn_stage,
        "turn_transition_chain": [
            "waiting_heartbeat",
            "restore_identity_and_commitments",
            "listening_state",
            "inner_speech_draft",
            "expression_monitoring",
            "utterance_release",
            "responsibility_relation_writeback",
        ],
        "life_context_ref": life_context_ref,
        "relation_turn_ref": relation_turn_ref,
        "context_accumulation_ref": "runtime/state/terminal/context_accumulation_window.json",
        "context_accumulation_restore_refs": context_accumulation_restore_refs,
        "session_envelope_ref": "runtime/state/terminal/session_envelope.json",
        "safe_terminal_loop_ref": "runtime/state/terminal/safe_terminal_loop_state.json",
        "relation_scope_ref": relation_scope_ref,
        "expression_monitor_restore_refs": expression_monitor_restore_refs,
        "language_percept_restore_refs": language_percept_restore_refs,
        "semantic_map_restore_refs": semantic_map_restore_refs,
        "unresolved_commitment_refs": unresolved_commitment_refs,
        "waiting_heartbeat_ref": waiting_heartbeat_ref,
        "next_required_action": next_required_action,
        "source_doc_refs": source_doc_refs,
        "readme_block_refs": readme_block_refs,
        "runtime_carrier_refs": runtime_carrier_refs,
    }
