from __future__ import annotations

from pathlib import Path


def build_runtime_paths(tmp_path: Path) -> dict[str, Path]:
    state_root = tmp_path / "runtime" / "state"
    runtime_root = tmp_path / "runtime"
    return {
        "runtime_root": runtime_root,
        "doc_out": runtime_root / "docs",
        "reports": runtime_root / "reports" / "latest",
        "receipts": runtime_root / "receipts",
        "direction_state": state_root / "direction",
        "authority_state": state_root / "authority",
        "neural_state": state_root / "neural_life_core",
        "state_root": state_root,
        "membrane_state": state_root / "membrane",
        "language_state": state_root / "language",
        "relationship_state": state_root / "relationship",
        "terminal_state": state_root / "terminal",
        "life_targets_state": state_root / "life_targets",
        "validation_state": state_root / "validation",
        "observation_state": state_root / "observation",
        "schema_runner_state": state_root / "schema_runner",
    }


def activation_bootstrap_commands(
    *,
    docs_dir: Path,
    paths: dict[str, Path],
    run_id_prefix: str,
) -> list[list[str]]:
    return [
        [
            "ingest-docs",
            "--docs",
            str(docs_dir),
            "--out",
            str(paths["doc_out"]),
            "--reports",
            str(paths["reports"]),
            "--receipts",
            str(paths["receipts"]),
            "--run-id",
            f"{run_id_prefix}-ingest",
            "--strict",
        ],
        [
            "build-direction-lock",
            "--docs",
            str(docs_dir),
            "--doc-index",
            str(paths["doc_out"] / "doc_carrier_index.json"),
            "--out",
            str(paths["direction_state"]),
            "--reports",
            str(paths["reports"]),
            "--receipts",
            str(paths["receipts"]),
            "--run-id",
            f"{run_id_prefix}-direction",
            "--strict",
        ],
        [
            "build-source-authority",
            "--docs",
            str(docs_dir),
            "--doc-index",
            str(paths["doc_out"] / "doc_carrier_index.json"),
            "--direction",
            str(paths["direction_state"]),
            "--out",
            str(paths["authority_state"]),
            "--reports",
            str(paths["reports"]),
            "--receipts",
            str(paths["receipts"]),
            "--run-id",
            f"{run_id_prefix}-authority",
            "--strict",
        ],
        [
            "build-neural-life-core",
            "--docs",
            str(docs_dir),
            "--doc-index",
            str(paths["doc_out"] / "doc_carrier_index.json"),
            "--authority",
            str(paths["authority_state"]),
            "--out",
            str(paths["neural_state"]),
            "--reports",
            str(paths["reports"]),
            "--receipts",
            str(paths["receipts"]),
            "--run-id",
            f"{run_id_prefix}-neural",
            "--strict",
        ],
        [
            "check-neural-life-core",
            "--state",
            str(paths["neural_state"]),
            "--reports",
            str(paths["reports"]),
            "--strict",
        ],
        [
            "build-state-store",
            "--docs",
            str(docs_dir),
            "--doc-index",
            str(paths["doc_out"] / "doc_carrier_index.json"),
            "--neural-core",
            str(paths["neural_state"]),
            "--out",
            str(paths["state_root"]),
            "--reports",
            str(paths["reports"]),
            "--receipts",
            str(paths["receipts"]),
            "--run-id",
            f"{run_id_prefix}-state",
            "--strict",
        ],
        [
            "check-state-store",
            "--state",
            str(paths["state_root"]),
            "--reports",
            str(paths["reports"]),
            "--strict",
        ],
        [
            "build-life-membrane",
            "--docs",
            str(docs_dir),
            "--doc-index",
            str(paths["doc_out"] / "doc_carrier_index.json"),
            "--direction",
            str(paths["direction_state"]),
            "--neural-core",
            str(paths["neural_state"]),
            "--state",
            str(paths["state_root"]),
            "--out",
            str(paths["membrane_state"]),
            "--reports",
            str(paths["reports"]),
            "--receipts",
            str(paths["receipts"]),
            "--run-id",
            f"{run_id_prefix}-membrane",
            "--strict",
        ],
        [
            "check-life-membrane",
            "--membrane",
            str(paths["membrane_state"]),
            "--state",
            str(paths["state_root"]),
            "--reports",
            str(paths["reports"]),
            "--strict",
        ],
        [
            "build-language-relationship",
            "--docs",
            str(docs_dir),
            "--doc-index",
            str(paths["doc_out"] / "doc_carrier_index.json"),
            "--neural-core",
            str(paths["neural_state"]),
            "--state",
            str(paths["state_root"]),
            "--membrane",
            str(paths["membrane_state"]),
            "--out",
            str(paths["state_root"]),
            "--reports",
            str(paths["reports"]),
            "--receipts",
            str(paths["receipts"]),
            "--run-id",
            f"{run_id_prefix}-language",
            "--strict",
        ],
        [
            "check-language-relationship",
            "--state",
            str(paths["state_root"]),
            "--membrane",
            str(paths["membrane_state"]),
            "--reports",
            str(paths["reports"]),
            "--strict",
        ],
        [
            "check-birth-readiness",
            "--docs",
            str(docs_dir),
            "--doc-index",
            str(paths["doc_out"] / "doc_carrier_index.json"),
            "--direction",
            str(paths["direction_state"]),
            "--neural-core",
            str(paths["neural_state"]),
            "--state",
            str(paths["state_root"]),
            "--membrane",
            str(paths["membrane_state"]),
            "--out",
            str(paths["life_targets_state"]),
            "--reports",
            str(paths["reports"]),
            "--receipts",
            str(paths["receipts"]),
            "--run-id",
            f"{run_id_prefix}-birth",
            "--strict",
        ],
        [
            "run-validation-membrane",
            "--docs",
            str(docs_dir),
            "--doc-index",
            str(paths["doc_out"] / "doc_carrier_index.json"),
            "--state",
            str(paths["state_root"]),
            "--membrane",
            str(paths["membrane_state"]),
            "--life-targets",
            str(paths["life_targets_state"]),
            "--validation",
            str(paths["validation_state"]),
            "--observation",
            str(paths["observation_state"]),
            "--reports",
            str(paths["reports"]),
            "--receipts",
            str(paths["receipts"]),
            "--run-id",
            f"{run_id_prefix}-validation",
            "--strict",
        ],
        [
            "check-validation-membrane",
            "--state",
            str(paths["state_root"]),
            "--validation",
            str(paths["validation_state"]),
            "--observation",
            str(paths["observation_state"]),
            "--reports",
            str(paths["reports"]),
            "--strict",
        ],
        [
            "build-schema-runner",
            "--docs",
            str(docs_dir),
            "--doc-index",
            str(paths["doc_out"] / "doc_carrier_index.json"),
            "--state",
            str(paths["state_root"]),
            "--reports",
            str(paths["reports"]),
            "--receipts",
            str(paths["receipts"]),
            "--run-id",
            f"{run_id_prefix}-schema",
            "--strict",
        ],
        [
            "check-schema-runner",
            "--state",
            str(paths["schema_runner_state"]),
            "--reports",
            str(paths["reports"]),
            "--strict",
        ],
        [
            "run-schema-smoke",
            "--state",
            str(paths["state_root"]),
            "--reports",
            str(paths["reports"]),
            "--receipts",
            str(paths["receipts"]),
            "--run-id",
            f"{run_id_prefix}-smoke",
            "--strict",
        ],
        [
            "build-life-support",
            "--docs",
            str(docs_dir),
            "--doc-index",
            str(paths["doc_out"] / "doc_carrier_index.json"),
            "--state",
            str(paths["state_root"]),
            "--validation",
            str(paths["reports"] / "validation_membrane_report.json"),
            "--out",
            str(paths["state_root"]),
            "--reports",
            str(paths["reports"]),
            "--receipts",
            str(paths["receipts"]),
            "--run-id",
            f"{run_id_prefix}-support",
            "--strict",
        ],
        [
            "check-life-support",
            "--state",
            str(paths["state_root"]),
            "--reports",
            str(paths["reports"]),
            "--strict",
        ],
        [
            "run-cycle",
            "--state",
            str(paths["state_root"]),
            "--reports",
            str(paths["reports"]),
            "--receipts",
            str(paths["receipts"]),
            "--run-id",
            f"{run_id_prefix}-cycle",
            "--shadow-only",
            "--strict",
        ],
        [
            "check-v0-contracts",
            "--docs",
            str(docs_dir),
            "--doc-index",
            str(paths["doc_out"] / "doc_carrier_index.json"),
            "--state",
            str(paths["state_root"]),
            "--reports",
            str(paths["reports"]),
            "--receipts",
            str(paths["receipts"]),
            "--run-id",
            f"{run_id_prefix}-contracts",
            "--strict",
        ],
        [
            "first-activation-preflight",
            "--docs",
            str(docs_dir),
            "--doc-index",
            str(paths["doc_out"] / "doc_carrier_index.json"),
            "--state",
            str(paths["state_root"]),
            "--reports",
            str(paths["reports"]),
            "--receipts",
            str(paths["receipts"]),
            "--run-id",
            f"{run_id_prefix}-preflight",
            "--strict",
        ],
        [
            "run-replay-shadow",
            "--state",
            str(paths["state_root"]),
            "--reports",
            str(paths["reports"]),
            "--receipts",
            str(paths["receipts"]),
            "--run-id",
            f"{run_id_prefix}-replay",
            "--strict",
        ],
        [
            "write-growth-archive",
            "--state",
            str(paths["state_root"]),
            "--reports",
            str(paths["reports"]),
            "--receipts",
            str(paths["receipts"]),
            "--run-id",
            f"{run_id_prefix}-archive",
            "--strict",
        ],
        [
            "emit-report",
            "--state",
            str(paths["state_root"]),
            "--reports",
            str(paths["reports"]),
            "--receipts",
            str(paths["receipts"]),
            "--run-id",
            f"{run_id_prefix}-emit",
            "--strict",
        ],
        [
            "explain-stage",
            "--reports",
            str(paths["reports"]),
            "--receipts",
            str(paths["receipts"]),
            "--run-id",
            f"{run_id_prefix}-stage",
            "--strict",
        ],
    ]
